import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import column, table

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7627c98ded5'
down_revision: Union[str, Sequence[str], None] = '3dbef3c9af77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    interests_table = table(
        'interests',
        column('id', sa.dialects.postgresql.UUID),
        column('name_translations', sa.dialects.postgresql.JSONB)
    )

    translated_interests = [
        {"en": "Programming", "ru": "Программирование"},
        {"en": "Web Development", "ru": "Веб-разработка"},
        {"en": "Mobile App Development", "ru": "Разработка мобильных приложений"},
        {"en": "Artificial Intelligence", "ru": "Искусственный интеллект"},
        {"en": "Machine Learning", "ru": "Машинное обучение"},
        {"en": "Data Science", "ru": "Наука о данных"},
        {"en": "Cybersecurity", "ru": "Кибербезопасность"},
        {"en": "Blockchain", "ru": "Блокчейн"},
        {"en": "Cloud Computing", "ru": "Облачные вычисления"},
        {"en": "DevOps", "ru": "DevOps"},
        {"en": "Internet of Things", "ru": "Интернет вещей"},
        {"en": "Augmented Reality", "ru": "Дополненная реальность"},
        {"en": "Virtual Reality", "ru": "Виртуальная реальность"},
        {"en": "Game Development", "ru": "Разработка игр"},
        {"en": "Computer Graphics", "ru": "Компьютерная графика"},
        {"en": "Digital Marketing", "ru": "Цифровой маркетинг"},
        {"en": "SEO Optimization", "ru": "SEO-оптимизация"},
        {"en": "UX/UI Design", "ru": "UX/UI дизайн"},
        {"en": "3D Modeling", "ru": "3D-моделирование"},
        {"en": "Animation", "ru": "Анимация"},
        {"en": "Painting", "ru": "Живопись"},
        {"en": "Drawing", "ru": "Рисование"},
        {"en": "Photography", "ru": "Фотография"},
        {"en": "Graphic Design", "ru": "Графический дизайн"},
        {"en": "Digital Art", "ru": "Цифровое искусство"},
        {"en": "Sculpture", "ru": "Скульптура"},
        {"en": "Calligraphy", "ru": "Каллиграфия"},
        {"en": "Pottery", "ru": "Гончарное дело"},
        {"en": "Origami", "ru": "Оригами"},
        {"en": "Knitting", "ru": "Вязание"},
        {"en": "Crocheting", "ru": "Вязание крючком"},
        {"en": "Embroidery", "ru": "Вышивание"},
        {"en": "Sewing", "ru": "Шитьё"},
        {"en": "Quilting", "ru": "Лоскутное шитьё"},
        {"en": "Woodworking", "ru": "Работа по дереву"},
        {"en": "Metalworking", "ru": "Металлообработка"},
        {"en": "Jewelry Making", "ru": "Изготовление украшений"},
        {"en": "Soap Making", "ru": "Мыловарение"},
        {"en": "Candle Making", "ru": "Изготовление свечей"},
        {"en": "Leatherworking", "ru": "Кожевенное дело"},
        {"en": "Glassblowing", "ru": "Стеклодувное дело"},
        {"en": "Mosaic Art", "ru": "Мозаика"},
        {"en": "Street Art", "ru": "Стрит-арт"},
        {"en": "Graffiti", "ru": "Граффити"},
        {"en": "Tattoo Art", "ru": "Татуировка"},
        {"en": "Floristry", "ru": "Флористика"},
        {"en": "Bonsai", "ru": "Бонсай"},
        {"en": "Gardening", "ru": "Садоводство"},
        {"en": "Landscape Design", "ru": "Ландшафтный дизайн"},
        {"en": "Indoor Plants", "ru": "Комнатные растения"},
        {"en": "Terrarium Making", "ru": "Изготовление террариумов"},
        {"en": "Birdwatching", "ru": "Наблюдение за птицами"},
        {"en": "Beekeeping", "ru": "Пчеловодство"},
        {"en": "Aquarium Keeping", "ru": "Аквариумистика"},
        {"en": "Pet Care", "ru": "Уход за домашними животными"},
        {"en": "Dog Training", "ru": "Дрессировка собак"},
        {"en": "Horseback Riding", "ru": "Верховая езда"},
        {"en": "Falconry", "ru": "Соколиная охота"},
        {"en": "Hiking", "ru": "Походы"},
        {"en": "Mountain Climbing", "ru": "Альпинизм"},
        {"en": "Camping", "ru": "Кемпинг"},
        {"en": "Fishing", "ru": "Рыбалка"},
        {"en": "Hunting", "ru": "Охота"},
        {"en": "Survival Skills", "ru": "Навыки выживания"},
        {"en": "Archery", "ru": "Стрельба из лука"},
        {"en": "Shooting Sports", "ru": "Стрелковый спорт"},
        {"en": "Running", "ru": "Бег"},
        {"en": "Jogging", "ru": "Бег трусцой"},
        {"en": "Marathon Running", "ru": "Марафонский бег"},
        {"en": "Trail Running", "ru": "Трейлраннинг"},
        {"en": "Swimming", "ru": "Плавание"},
        {"en": "Diving", "ru": "Дайвинг"},
        {"en": "Surfing", "ru": "Сёрфинг"},
        {"en": "Windsurfing", "ru": "Виндсёрфинг"},
        {"en": "Kitesurfing", "ru": "Кайтсёрфинг"},
        {"en": "Sailing", "ru": "Парусный спорт"},
        {"en": "Rowing", "ru": "Гребля"},
        {"en": "Kayaking", "ru": "Каякинг"},
        {"en": "Canoeing", "ru": "Каноэ"},
        {"en": "Cycling", "ru": "Велоспорт"},
        {"en": "Mountain Biking", "ru": "Маунтинбайк"},
        {"en": "BMX", "ru": "BMX"},
        {"en": "Skateboarding", "ru": "Скейтбординг"},
        {"en": "Rollerblading", "ru": "Катание на роликах"},
        {"en": "Ice Skating", "ru": "Катание на коньках"},
        {"en": "Skiing", "ru": "Лыжный спорт"},
        {"en": "Snowboarding", "ru": "Сноубординг"},
        {"en": "Yoga", "ru": "Йога"},
        {"en": "Pilates", "ru": "Пилатес"},
        {"en": "Meditation", "ru": "Медитация"},
        {"en": "Tai Chi", "ru": "Тайцзи"},
        {"en": "Gymnastics", "ru": "Гимнастика"},
        {"en": "Acrobatics", "ru": "Акробатика"},
        {"en": "Parkour", "ru": "Паркур"},
        {"en": "Dance", "ru": "Танцы"},
        {"en": "Ballet", "ru": "Балет"},
        {"en": "Hip-Hop Dance", "ru": "Хип-хоп танцы"},
        {"en": "Ballroom Dancing", "ru": "Бальные танцы"},
        {"en": "Zumba", "ru": "Зумба"},
        {"en": "Basketball", "ru": "Баскетбол"},
        {"en": "Football", "ru": "Футбол"},
        {"en": "Tennis", "ru": "Теннис"},
        {"en": "Table Tennis", "ru": "Настольный теннис"},
        {"en": "Badminton", "ru": "Бадминтон"},
        {"en": "Volleyball", "ru": "Волейбол"},
        {"en": "Beach Volleyball", "ru": "Пляжный волейбол"},
        {"en": "Rugby", "ru": "Регби"},
        {"en": "Cricket", "ru": "Крикет"},
        {"en": "Baseball", "ru": "Бейсбол"},
        {"en": "Softball", "ru": "Софтбол"},
        {"en": "Golf", "ru": "Гольф"},
        {"en": "Mini Golf", "ru": "Мини-гольф"},
        {"en": "Bowling", "ru": "Боулинг"},
        {"en": "Boxing", "ru": "Бокс"},
        {"en": "Martial Arts", "ru": "Боевые искусства"},
        {"en": "Judo", "ru": "Дзюдо"},
        {"en": "Karate", "ru": "Каратэ"},
        {"en": "Taekwondo", "ru": "Тхэквондо"},
        {"en": "Wrestling", "ru": "Борьба"},
        {"en": "Fencing", "ru": "Фехтование"},
        {"en": "Esports", "ru": "Киберспорт"},
        {"en": "Video Games", "ru": "Видеоигры"},
        {"en": "Board Games", "ru": "Настольные игры"},
        {"en": "Chess", "ru": "Шахматы"},
        {"en": "Card Games", "ru": "Карточные игры"},
        {"en": "Poker", "ru": "Покер"},
        {"en": "Magic: The Gathering", "ru": "Magic: The Gathering"},
        {"en": "Role-Playing Games", "ru": "Ролевые игры"},
        {"en": "Puzzles", "ru": "Головоломки"},
        {"en": "Sudoku", "ru": "Судоку"},
        {"en": "Crosswords", "ru": "Кроссворды"},
        {"en": "Strategy Games", "ru": "Стратегические игры"},
        {"en": "Cooking", "ru": "Кулинария"},
        {"en": "Baking", "ru": "Выпечка"},
        {"en": "Grilling", "ru": "Гриль"},
        {"en": "Barbecue", "ru": "Барбекю"},
        {"en": "Vegan Cuisine", "ru": "Веганская кухня"},
        {"en": "Vegetarian Cuisine", "ru": "Вегетарианская кухня"},
        {"en": "International Cuisine", "ru": "Международная кухня"},
        {"en": "Italian Cuisine", "ru": "Итальянская кухня"},
        {"en": "Japanese Cuisine", "ru": "Японская кухня"},
        {"en": "Mexican Cuisine", "ru": "Мексиканская кухня"},
        {"en": "Indian Cuisine", "ru": "Индийская кухня"},
        {"en": "French Cuisine", "ru": "Французская кухня"},
        {"en": "Chinese Cuisine", "ru": "Китайская кухня"},
        {"en": "Thai Cuisine", "ru": "Тайская кухня"},
        {"en": "Korean Cuisine", "ru": "Корейская кухня"},
        {"en": "Mediterranean Cuisine", "ru": "Средиземноморская кухня"},
        {"en": "Wine Tasting", "ru": "Дегустация вин"},
        {"en": "Beer Brewing", "ru": "Пивоварение"},
        {"en": "Coffee Brewing", "ru": "Приготовление кофе"},
        {"en": "Tea Culture", "ru": "Чайная культура"},
        {"en": "Cheese Tasting", "ru": "Дегустация сыров"},
        {"en": "Chocolate Making", "ru": "Изготовление шоколада"},
        {"en": "Travel", "ru": "Путешествия"},
        {"en": "Backpacking", "ru": "Бэкпэкинг"},
        {"en": "Road Trips", "ru": "Автопутешествия"},
        {"en": "Cruises", "ru": "Круизы"},
        {"en": "Ecotourism", "ru": "Экотуризм"},
        {"en": "Adventure Travel", "ru": "Приключенческий туризм"},
        {"en": "Cultural Tourism", "ru": "Культурный туризм"},
        {"en": "Photography Travel", "ru": "Фототуризм"},
        {"en": "Language Learning", "ru": "Изучение языков"},
        {"en": "Linguistics", "ru": "Лингвистика"},
        {"en": "History", "ru": "История"},
        {"en": "Ancient History", "ru": "Древняя история"},
        {"en": "Medieval History", "ru": "Средневековая история"},
        {"en": "World War II", "ru": "Вторая мировая война"},
        {"en": "Archaeology", "ru": "Археология"},
        {"en": "Anthropology", "ru": "Антропология"},
        {"en": "Sociology", "ru": "Социология"},
        {"en": "Psychology", "ru": "Психология"},
        {"en": "Philosophy", "ru": "Философия"},
        {"en": "Ethics", "ru": "Этика"},
        {"en": "Logic", "ru": "Логика"},
        {"en": "Political Science", "ru": "Политология"},
        {"en": "Economics", "ru": "Экономика"},
        {"en": "Physics", "ru": "Физика"},
        {"en": "Quantum Physics", "ru": "Квантовая физика"},
        {"en": "Astrophysics", "ru": "Астрофизика"},
        {"en": "Chemistry", "ru": "Химия"},
        {"en": "Organic Chemistry", "ru": "Органическая химия"},
        {"en": "Biochemistry", "ru": "Биохимия"},
        {"en": "Biology", "ru": "Биология"},
        {"en": "Genetics", "ru": "Генетика"},
        {"en": "Microbiology", "ru": "Микробиология"},
        {"en": "Ecology", "ru": "Экология"},
        {"en": "Mathematics", "ru": "Математика"},
        {"en": "Statistics", "ru": "Статистика"},
        {"en": "Geometry", "ru": "Геометрия"},
        {"en": "Algebra", "ru": "Алгебра"},
        {"en": "Astronomy", "ru": "Астрономия"},
        {"en": "Space Exploration", "ru": "Космические исследования"},
        {"en": "Meteorology", "ru": "Метеорология"},
        {"en": "Climate Science", "ru": "Климатология"},
        {"en": "Geology", "ru": "Геология"},
        {"en": "Oceanography", "ru": "Океанография"},
        {"en": "Robotics", "ru": "Робототехника"},
        {"en": "Drones", "ru": "Дроны"},
        {"en": "Electric Vehicles", "ru": "Электромобили"},
        {"en": "Space Technology", "ru": "Космические технологии"},
        {"en": "Biotechnology", "ru": "Биотехнологии"},
        {"en": "Nanotechnology", "ru": "Нанотехнологии"},
        {"en": "Renewable Energy", "ru": "Возобновляемая энергия"},
        {"en": "Solar Power", "ru": "Солнечная энергия"},
        {"en": "Wind Power", "ru": "Ветроэнергетика"},
        {"en": "Literature", "ru": "Литература"},
        {"en": "Poetry", "ru": "Поэзия"},
        {"en": "Fiction Writing", "ru": "Писательство"},
        {"en": "Screenwriting", "ru": "Сценарное мастерство"},
        {"en": "Journalism", "ru": "Журналистика"},
        {"en": "Blogging", "ru": "Блоггинг"},
        {"en": "Comic Books", "ru": "Комиксы"},
        {"en": "Manga", "ru": "Манга"},
        {"en": "Music", "ru": "Музыка"},
        {"en": "Playing Guitar", "ru": "Игра на гитаре"},
        {"en": "Playing Piano", "ru": "Игра на фортепиано"},
        {"en": "Playing Drums", "ru": "Игра на барабанах"},
        {"en": "Violin", "ru": "Скрипка"},
        {"en": "Singing", "ru": "Пение"},
        {"en": "Songwriting", "ru": "Написание песен"},
        {"en": "Music Production", "ru": "Музыкальное производство"},
        {"en": "DJing", "ru": "Диск-жокей"},
        {"en": "Opera", "ru": "Опера"},
        {"en": "Theater", "ru": "Театр"},
        {"en": "Stand-Up Comedy", "ru": "Стендап-комедия"},
        {"en": "Improvisation", "ru": "Импровизация"},
        {"en": "Circus Arts", "ru": "Цирковое искусство"},
        {"en": "Magic Tricks", "ru": "Фокусы"},
        {"en": "Film Making", "ru": "Кинопроизводство"},
        {"en": "Documentary Films", "ru": "Документальное кино"},
        {"en": "Animation Movies", "ru": "Анимационные фильмы"},
        {"en": "Classic Movies", "ru": "Классическое кино"},
        {"en": "Science Fiction", "ru": "Научная фантастика"},
        {"en": "Fantasy Literature", "ru": "Фэнтези"},
        {"en": "Horror", "ru": "Ужасы"},
        {"en": "Thriller", "ru": "Триллеры"},
        {"en": "Romance Novels", "ru": "Любовные романы"},
        {"en": "Historical Fiction", "ru": "Историческая проза"},
        {"en": "Biographies", "ru": "Биографии"},
        {"en": "Self-Help Books", "ru": "Книги по саморазвитию"},
        {"en": "Travel Writing", "ru": "Трэвел-литература"},
        {"en": "Photography Art", "ru": "Художественная фотография"},
        {"en": "Interior Design", "ru": "Дизайн интерьера"},
        {"en": "Fashion Design", "ru": "Модный дизайн"},
        {"en": "Makeup Artistry", "ru": "Визаж"},
        {"en": "Hairstyling", "ru": "Парикмахерское искусство"},
        {"en": "Nail Art", "ru": "Нейл-арт"},
        {"en": "Cosplay", "ru": "Косплей"},
        {"en": "Model Building", "ru": "Сборка моделей"},
        {"en": "Stamp Collecting", "ru": "Коллекционирование марок"},
        {"en": "Coin Collecting", "ru": "Коллекционирование монет"},
        {"en": "Antiquing", "ru": "Антиквариат"},
        {"en": "Vintage Shopping", "ru": "Винтажные покупки"},
        {"en": "Thrift Shopping", "ru": "Секонд-хенд"},
        {"en": "Home Brewing", "ru": "Домашнее пивоварение"},
        {"en": "Home Improvement", "ru": "Ремонт и обустройство дома"},
        {"en": "DIY Projects", "ru": "Самоделки"},
        {"en": "Car Restoration", "ru": "Реставрация автомобилей"},
        {"en": "Motorcycle Riding", "ru": "Езда на мотоцикле"},
        {"en": "Off-Roading", "ru": "Внедорожные приключения"},
        {"en": "Formula 1", "ru": "Формула 1"},
        {"en": "NASCAR", "ru": "NASCAR"},
        {"en": "Basketball Analytics", "ru": "Баскетбольная аналитика"},
        {"en": "Football Tactics", "ru": "Футбольная тактика"},
        {"en": "Chess Openings", "ru": "Шахматные дебюты"},
        {"en": "Poker Strategy", "ru": "Покерная стратегия"},
        {"en": "Astrology", "ru": "Астрология"},
        {"en": "Numerology", "ru": "Нумерология"},
        {"en": "Mythology", "ru": "Мифология"},
        {"en": "Urban Legends", "ru": "Городские легенды"},
        {"en": "Conspiracy Theories", "ru": "Теории заговора"},
        {"en": "True Crime", "ru": "Тру-крайм истории"},
        {"en": "Forensic Science", "ru": "Криминалистика"},
        {"en": "Volunteering", "ru": "Волонтёрство"},
        {"en": "Charity Work", "ru": "Благотворительность"},
        {"en": "Environmental Activism", "ru": "Экологический активизм"},
        {"en": "Animal Rights", "ru": "Защита животных"},
        {"en": "Human Rights", "ru": "Права человека"},
        {"en": "Public Speaking", "ru": "Ораторское мастерство"},
        {"en": "Debate", "ru": "Дебаты"},
        {"en": "Leadership", "ru": "Лидерство"},
        {"en": "Team Building", "ru": "Командообразование"},
        {"en": "Entrepreneurship", "ru": "Предпринимательство"},
        {"en": "Startups", "ru": "Стартапы"},
        {"en": "Investing", "ru": "Инвестиции"},
        {"en": "Cryptocurrency", "ru": "Криптовалюта"},
        {"en": "Stock Market", "ru": "Фондовый рынок"},
        {"en": "Real Estate", "ru": "Недвижимость"},
        {"en": "Minimalism", "ru": "Минимализм"},
        {"en": "Sustainability", "ru": "Устойчивое развитие"},
        {"en": "Zero Waste", "ru": "Ноль отходов"},
        {"en": "Self-Sufficiency", "ru": "Самодостаточность"},
        {"en": "Nutrition", "ru": "Нутрициология"},
        {"en": "Fitness", "ru": "Фитнес"},
        {"en": "Bodybuilding", "ru": "Бодибилдинг"},
        {"en": "CrossFit", "ru": "Кроссфит"},
        {"en": "Calisthenics", "ru": "Калистеника"},
        {"en": "Kinesiology", "ru": "Кинезиология"},
        {"en": "Physical Therapy", "ru": "Физиотерапия"},
        {"en": "Chiropractic", "ru": "Хиропрактика"},
        {"en": "Massage Therapy", "ru": "Массаж"},
        {"en": "Aromatherapy", "ru": "Ароматерапия"},
        {"en": "Herbalism", "ru": "Траволечение"},
        {"en": "Traditional Medicine", "ru": "Народная медицина"},
        {"en": "Mental Health", "ru": "Психическое здоровье"},
        {"en": "Mindfulness", "ru": "Осознанность"},
        {"en": "Life Coaching", "ru": "Коучинг"},
        {"en": "Parenting", "ru": "Родительство"},
        {"en": "Child Development", "ru": "Развитие детей"},
        {"en": "Adoption", "ru": "Усыновление"},
        {"en": "Pregnancy", "ru": "Беременность"},
        {"en": "Baby Care", "ru": "Уход за младенцами"},
        {"en": "Education", "ru": "Образование"},
        {"en": "Online Learning", "ru": "Онлайн-обучение"},
        {"en": "Tutoring", "ru": "Репетиторство"},
        {"en": "Special Education", "ru": "Специальное образование"},
        {"en": "Pedagogy", "ru": "Педагогика"},
        {"en": "Andragogy", "ru": "Андрагогика"},
        {"en": "Scouting", "ru": "Скаутинг"},
        {"en": "Campfire Stories", "ru": "Истории у костра"},
        {"en": "Karaoke", "ru": "Караоке"},
        {"en": "Trivia Nights", "ru": "Викторины"},
        {"en": "Escape Rooms", "ru": "Квест-комнаты"},
        {"en": "Laser Tag", "ru": "Лазертаг"},
        {"en": "Paintball", "ru": "Пейнтбол"},
        {"en": "Airsoft", "ru": "Страйкбол"},
        {"en": "Geocaching", "ru": "Геокэшинг"},
        {"en": "Urban Exploration", "ru": "Городские исследования"},
        {"en": "Ghost Hunting", "ru": "Охота за привидениями"},
        {"en": "Metal Detecting", "ru": "Металлоискатель"},
        {"en": "Rock Climbing", "ru": "Скалолазание"},
        {"en": "Bouldering", "ru": "Боулдеринг"},
        {"en": "Ice Climbing", "ru": "Ледолазание"},
        {"en": "Caving", "ru": "Спелеология"},
        {"en": "Whitewater Rafting", "ru": "Сплав по рекам"},
        {"en": "Paragliding", "ru": "Парапланеризм"},
        {"en": "Skydiving", "ru": "Прыжки с парашютом"},
        {"en": "Bungee Jumping", "ru": "Банджи-джампинг"},
        {"en": "Hang Gliding", "ru": "Дельтапланеризм"},
        {"en": "Hot Air Ballooning", "ru": "Полёты на воздушном шаре"},
        {"en": "Scuba Diving", "ru": "Подводное плавание"},
        {"en": "Snorkeling", "ru": "Сноркелинг"},
        {"en": "Free Diving", "ru": "Фридайвинг"},
        {"en": "Spearfishing", "ru": "Подводная охота"},
        {"en": "Paddleboarding", "ru": "Сапбординг"},
        {"en": "Wakeboarding", "ru": "Вейкбординг"},
        {"en": "Snowmobiling", "ru": "Снегоходы"},
        {"en": "Dog Sledding", "ru": "Ездовые собаки"},
        {"en": "Ice Fishing", "ru": "Подлёдная рыбалка"},
        {"en": "Sandboarding", "ru": "Сэндбординг"},
        {"en": "Mushroom Foraging", "ru": "Сбор грибов"},
        {"en": "Berry Picking", "ru": "Сбор ягод"},
        {"en": "Herb Foraging", "ru": "Сбор трав"},
        {"en": "Map Reading", "ru": "Чтение карт"},
        {"en": "Orienteering", "ru": "Спортивное ориентирование"},
        {"en": "Weather Watching", "ru": "Наблюдение за погодой"},
        {"en": "Storm Chasing", "ru": "Погоня за штормами"},
        {"en": "Volcano Watching", "ru": "Наблюдение за вулканами"},
        {"en": "Northern Lights", "ru": "Северное сияние"},
        {"en": "Stargazing", "ru": "Наблюдение звёзд"},
        {"en": "Telescope Building", "ru": "Сборка телескопов"},
        {"en": "Planetarium", "ru": "Планетарий"},
        {"en": "Cosplay Photography", "ru": "Косплей-фотография"},
        {"en": "Stop Motion Animation", "ru": "Покадровая анимация"},
        {"en": "Creative Writing", "ru": "Творческое письмо"},
        {"en": "Bullet Journaling", "ru": "Bullet Journal"},
        {"en": "Scrapbooking", "ru": "Скрапбукинг"},
        {"en": "Coloring Books", "ru": "Раскраски"},
        {"en": "Card Making", "ru": "Изготовление открыток"},
        {"en": "Gift Wrapping", "ru": "Упаковка подарков"},
        {"en": "Event Planning", "ru": "Организация мероприятий"},
        {"en": "Wedding Planning", "ru": "Организация свадеб"},
        {"en": "Party Decoration", "ru": "Декорирование вечеринок"},
        {"en": "Baking Competition", "ru": "Конкурсы выпечки"},
        {"en": "Cooking Challenge", "ru": "Кулинарные челленджи"},
        {"en": "Food Photography", "ru": "Фуд-фотография"},
        {"en": "Restaurant Reviewing", "ru": "Ресторанные обзоры"},
        {"en": "Product Reviewing", "ru": "Обзоры товаров"},
        {"en": "Unboxing", "ru": "Распаковка"},
        {"en": "Livestreaming", "ru": "Стриминг"},
        {"en": "Podcasting", "ru": "Подкастинг"},
        {"en": "Voice Acting", "ru": "Озвучивание"},
        {"en": "Sound Design", "ru": "Звуковой дизайн"},
        {"en": "Foley Art", "ru": "Шумовое оформление"},
        {"en": "Bookbinding", "ru": "Переплётное дело"},
        {"en": "Paper Making", "ru": "Изготовление бумаги"},
        {"en": "Rubik's Cube Solving", "ru": "Спидкубинг"},
        {"en": "Juggling", "ru": "Жонглирование"},
        {"en": "Yo-Yoing", "ru": "Йо-йо"},
        {"en": "Kendama", "ru": "Кендама"},
        {"en": "Diabolo", "ru": "Диаболо"},
        {"en": "Poi Spinning", "ru": "Кручение пои"},
        {"en": "Fire Dancing", "ru": "Огненные танцы"},
        {"en": "Stilt Walking", "ru": "Ходули"},
        {"en": "Face Painting", "ru": "Аквагрим"},
        {"en": "Balloon Twisting", "ru": "Моделирование из шаров"},
        {"en": "Ventriloquism", "ru": "Чревовещание"},
        {"en": "Puppetry", "ru": "Кукольный театр"},
        {"en": "Storytelling", "ru": "Сторителлинг"},
        {"en": "Personal Finance", "ru": "Личные финансы"},
        {"en": "Tax Preparation", "ru": "Подготовка налогов"},
        {"en": "Gardening Design", "ru": "Дизайн сада"},
        {"en": "Hydroponics", "ru": "Гидропоника"},
        {"en": "Aquaponics", "ru": "Аквапоника"},
        {"en": "Permaculture", "ru": "Пермакультура"},
        {"en": "Composting", "ru": "Компостирование"},
        {"en": "Rainwater Harvesting", "ru": "Сбор дождевой воды"},
        {"en": "Solar Cooking", "ru": "Солнечная готовка"},
        {"en": "Houseplants", "ru": "Комнатные растения"},
        {"en": "Succulent Collecting", "ru": "Коллекция суккулентов"},
        {"en": "Orchid Growing", "ru": "Выращивание орхидей"},
        {"en": "Rose Gardening", "ru": "Розарий"},
        {"en": "Vegetable Gardening", "ru": "Огородничество"},
        {"en": "Fruit Tree Growing", "ru": "Выращивание фруктовых деревьев"},
        {"en": "Farm Life", "ru": "Фермерская жизнь"},
        {"en": "Chicken Keeping", "ru": "Разведение кур"},
        {"en": "Goat Keeping", "ru": "Разведение коз"},
        {"en": "Horse Care", "ru": "Уход за лошадьми"},
        {"en": "Veterinary Science", "ru": "Ветеринария"},
        {"en": "Wildlife Photography", "ru": "Фото дикой природы"},
        {"en": "Underwater Photography", "ru": "Подводная фотография"},
        {"en": "Aerial Photography", "ru": "Аэрофотосъёмка"},
        {"en": "Time-Lapse Photography", "ru": "Таймлапс-фотография"},
        {"en": "Macro Photography", "ru": "Макрофотография"},
        {"en": "Documentary Photography", "ru": "Документальная фотография"},
        {"en": "Street Photography", "ru": "Уличная фотография"},
        {"en": "Portrait Photography", "ru": "Портретная фотография"},
        {"en": "Fashion Photography", "ru": "Фэшн-фотография"},
        {"en": "Product Photography", "ru": "Предметная фотография"},
        {"en": "Editing Photos", "ru": "Редактирование фото"},
        {"en": "Photoshop", "ru": "Photoshop"},
        {"en": "Lightroom", "ru": "Lightroom"},
        {"en": "Video Editing", "ru": "Видеомонтаж"},
        {"en": "Color Grading", "ru": "Цветокоррекция"},
        {"en": "Visual Effects", "ru": "Визуальные эффекты"},
        {"en": "Motion Graphics", "ru": "Моушн-графика"},
        {"en": "App Design", "ru": "Дизайн приложений"},
        {"en": "Web Design", "ru": "Веб-дизайн"},
        {"en": "Logo Design", "ru": "Логотипы"},
        {"en": "Typography", "ru": "Типографика"},
        {"en": "Illustration", "ru": "Иллюстрация"},
        {"en": "Character Design", "ru": "Дизайн персонажей"},
        {"en": "Cartooning", "ru": "Карикатуры"},
        {"en": "Comic Book Creation", "ru": "Создание комиксов"},
        {"en": "Zine Making", "ru": "Создание зинов"},
        {"en": "Fan Fiction", "ru": "Фанфики"},
        {"en": "Music Remixing", "ru": "Ремиксы"},
        {"en": "Beat Making", "ru": "Создание битов"},
        {"en": "Turntablism", "ru": "Тёрнтейблизм"},
        {"en": "Concert Going", "ru": "Посещение концертов"},
        {"en": "Festivals", "ru": "Фестивали"},
        {"en": "Renaissance Fairs", "ru": "Ярмарки Ренессанса"},
        {"en": "Comic Conventions", "ru": "Комик-коны"},
        {"en": "Anime Conventions", "ru": "Аниме-конвенты"},
        {"en": "Gaming Conventions", "ru": "Игровые выставки"},
        {"en": "Maker Faire", "ru": "Ярмарка самоделок"},
        {"en": "Book Fairs", "ru": "Книжные ярмарки"},
        {"en": "Craft Fairs", "ru": "Ярмарки ремёсел"},
        {"en": "Farmers Markets", "ru": "Фермерские рынки"},
        {"en": "Food Festivals", "ru": "Фестивали еды"},
        {"en": "Wine Festivals", "ru": "Винные фестивали"},
        {"en": "Beer Festivals", "ru": "Пивные фестивали"},
        {"en": "Cultural Festivals", "ru": "Культурные фестивали"},
        {"en": "Film Festivals", "ru": "Кинофестивали"},
        {"en": "Art Exhibitions", "ru": "Художественные выставки"},
        {"en": "Museum Tours", "ru": "Музейные туры"},
        {"en": "Historical Reenactment", "ru": "Историческая реконструкция"},
        {"en": "LARP", "ru": "Ролевые игры живого действия"},
        {"en": "Medieval Combat", "ru": "Средневековый бой"},
        {"en": "Sword Fighting", "ru": "Фехтование на мечах"},
        {"en": "Jousting", "ru": "Рыцарские турниры"},
        {"en": "Blacksmithing", "ru": "Кузнечное дело"},
        {"en": "Armor Making", "ru": "Изготовление доспехов"},
        {"en": "Leather Armor", "ru": "Кожаные доспехи"},
        {"en": "Chainmail", "ru": "Кольчуга"},
        {"en": "Viking Culture", "ru": "Культура викингов"},
        {"en": "Samurai Culture", "ru": "Культура самураев"},
        {"en": "Ninja", "ru": "Ниндзя"},
        {"en": "Pirate History", "ru": "История пиратов"},
        {"en": "Ancient Egypt", "ru": "Древний Египет"},
        {"en": "Greek Mythology", "ru": "Греческая мифология"},
        {"en": "Roman History", "ru": "Римская история"},
        {"en": "Celtic Mythology", "ru": "Кельтская мифология"},
        {"en": "Norse Mythology", "ru": "Скандинавская мифология"},
        {"en": "Slavic Mythology", "ru": "Славянская мифология"},
        {"en": "Egyptian Mythology", "ru": "Египетская мифология"},
        {"en": "Chinese Mythology", "ru": "Китайская мифология"},
        {"en": "Japanese Folklore", "ru": "Японский фольклор"},
        {"en": "Indian Mythology", "ru": "Индийская мифология"},
        {"en": "Aztec Mythology", "ru": "Ацтекская мифология"},
        {"en": "Mayan Mythology", "ru": "Майянская мифология"},
        {"en": "Inca Mythology", "ru": "Мифология инков"},
        {"en": "Religious Studies", "ru": "Религиоведение"},
        {"en": "Theology", "ru": "Теология"},
        {"en": "Bible Study", "ru": "Изучение Библии"},
        {"en": "Quran Study", "ru": "Изучение Корана"},
        {"en": "Buddhism", "ru": "Буддизм"},
        {"en": "Hinduism", "ru": "Индуизм"},
        {"en": "Islam", "ru": "Ислам"},
        {"en": "Judaism", "ru": "Иудаизм"},
        {"en": "Christianity", "ru": "Христианство"},
        {"en": "Sikhism", "ru": "Сикхизм"},
        {"en": "Shinto", "ru": "Синтоизм"},
        {"en": "Taoism", "ru": "Даосизм"},
        {"en": "Confucianism", "ru": "Конфуцианство"},
        {"en": "Paganism", "ru": "Язычество"},
        {"en": "Wicca", "ru": "Викка"},
        {"en": "Atheism", "ru": "Атеизм"},
        {"en": "Agnosticism", "ru": "Агностицизм"},
        {"en": "Spirituality", "ru": "Духовность"},
    ]

    op.bulk_insert(
        interests_table,
        [{"id": str(uuid.uuid4()), "name_translations": interest} for interest in translated_interests]
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM interests")
